base_channels: 64  # base_channels大一些有好处
epochs: 50 # 训练多少个epoch
batch_size: 16  # batch_size小一些
lr_adjust_epoch: 25 # 学习率调整的epoch
batch_print_interval: 100 # 打印间隔，以batch为单位
checkpoint_save_interval: 10 # 模型保存间隔，以epoch为单位
save_path: './checkpoints/v1.1-cfg'  # 模型保存路径
use_cfg: True  # 是否使用classifier-free guidance，开启就可以训练条件生成模型了
device: 'cuda' # cuda、cpu、mps(only macbook)
 